package demo.domainModel;

import java.util.Date;

import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class ModelUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yearmonthday.ID
     *
     * @mbg.generated Tue May 19 15:56:54 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yearmonthday.YEAR_MONTH_DAY
     *
     * @mbg.generated Tue May 19 15:56:54 JST 2020
     */
    private Date yearMonthDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yearmonthday.ID
     *
     * @return the value of yearmonthday.ID
     *
     * @mbg.generated Tue May 19 15:56:54 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yearmonthday.ID
     *
     * @param id the value for yearmonthday.ID
     *
     * @mbg.generated Tue May 19 15:56:54 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yearmonthday.YEAR_MONTH_DAY
     *
     * @return the value of yearmonthday.YEAR_MONTH_DAY
     *
     * @mbg.generated Tue May 19 15:56:54 JST 2020
     */
    public Date getYearMonthDay() {
        return yearMonthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yearmonthday.YEAR_MONTH_DAY
     *
     * @param yearMonthDay the value for yearmonthday.YEAR_MONTH_DAY
     *
     * @mbg.generated Tue May 19 15:56:54 JST 2020
     */
    public void setYearMonthDay(Date yearMonthDay) {
        this.yearMonthDay = yearMonthDay;
    }
}